### ISSUE TITLE
get_filename is not doing what is intended...

### ISSUE THREAD

**Issue by patrick99e99** [AustEcon/polyglot#4]
I used the upload_bcat command with a file path: `/Users/patrick/Desktop/landscape.mp3`

As you can see, the OP_RETURN data actually contains the full file path instead of just the file name.
https://whatsonchain.com/tx/ba135a019f9314030c6b3766b1a96d26ac1729fef9be1e6e35daa248e50368b5

**Comment by patrick99e99** [comment]
I uninstalled bitsv and installed it from master and tried another upload with polyglot's current master and this no longer seems to be an issue.

**Comment by mathiasrw** [comment]
This example should work - but because the filename starts with `/` it is not valid (see https://d.bico.media)

polyglot should make sure the `/` is stripped from the beginning of the filename. 

![image](https://user-images.githubusercontent.com/1063454/66365123-35463e80-e98c-11e9-9f04-5f33d9f58eec.png)

**Comment by AustEcon** [comment]
Aha! Thanks 😉

**Comment by patrick99e99** [comment]
I can see that being a potential problem for filesystems that use backslashes, a path like: `"\HERE\THERE\EVERYWHERE\/SOME_BOGUS.FILE"` would result in a file starting with "/"

but for me, my string was `/Users/patrick/Desktop/landscape.mp3` and the code is doing:

```
 81     def get_filename(path):
 82         if "\\" in path:
 83             lst = path.split(os.sep)
 84             return lst[len(lst) - 1]
 85         else:
 86             lst = path.split("/")
 87             return lst[len(lst) - 1]
```

So, my example is using the else condition, therefore that should not have been returning anything with a forward slash in it---  Thus my confusion of how this happened, and like I said-- it didn't happen a 2nd time with the exact same string.

**Comment by AustEcon** [comment]
Python pathlib is pretty awesome these days. 
That's probably a better way to do this. Just under time pressure I gravitate towards whatever gets the job done! 🤣

**Comment by xloem** [comment]
I've submitted a PR implementing switching to pathlib at #15
